### ISSUE TITLE
Add pause before stopping camera

### ISSUE THREAD

**Issue by cbimbo** [mkrumin/vBox#2]
Hey Michael,

Currently, the video stops before the camSync signal is actually sent, so we miss it. A quick fix is to add a `pause(.5)` before line 133 `obj.cameraObj.stopAcquisition();` of Camera.m. You mentioned making it a parameter, so I'm just posting this here for your record.
Thanks!

Célian

**Comment by mkrumin** [comment]
Implemented (#9), with the default value of 5 seconds - this should be more than enough to catch the LEDs OFF/ON event in the main video file (not in XXX_lastFrames.mj2). @cbimbo
